print("Hi, my name is Dylan Sabuda and I go to Gull Lake High School, and I am in the 9th grade.")
print("Once upon a time...\n")
print("There was a dog named Ahsoka (my dog). She was known in Spain as 'Senorita Meneo Perra'.\n")
print("In Sweden, she was known as 'Fröken Vicka Hund'.\n")
print("In Poland, she was known as 'Tęsknić Poruszaj Pies'.")
